### ISSUE TITLE
Fix error: module does not exist

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#53]
This happens when the code at [`pkg/module/utils.go`](https://github.com/Lilypad-Tech/lilypad/blob/main/pkg/module/utils.go) checks if the directory exists but not the actual code inside the repo (also checks that `.git` exists).

Potential fix: check for the `tmpl` file and if does not, trigger the process to clone the repo.

The current workaround (remove `/tmp/lilypad/data/repos`) works, because it removes the empty dir and the next execution clones the repo.

cc/ @noryev

**Comment by Zorlin** [comment]
Needs a Go engineer :)

**Comment by Zorlin** [comment]
I will give it a go though, might a good "first issue" and might help me learn more Go.

**Comment by logan-wrld** [comment]
@bgins and I are looking into reproducing this issue. 

- Run a job- 
- Delete all the data inside 
- Run the job again
- See what happens
Does the job just fail?

**Comment by bgins** [comment]
I'm unable to reproduce this issue. Tried the following:

- Remove all data from the `/tmp/lilypad/data/repos/lilypad-tech/lilypad-module-cowsay` and run job -> Module repo dowloaded again and job runs
- Remove `lilypad_module.json.tmpl` from the directory and run job -> `error loading module: worktree contains unstaged changes`

We want the last error because it indicates changes to the module, and we shouldn't run with unexpected changes.

Going to close this issue for now, but we can re-open if we can reproduce the issue.
