### ISSUE TITLE
[core] local IPFS node?

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#83]
Is this the reason why jobs take too long

**Comment by arsen3d** [comment]
![Image](https://github.com/Lilypad-Tech/lilypad/assets/298235/37177007-8983-4e50-8571-043b140087c2)

Yes. It's about the way "bacalhau get" attempts to get the file.
Workaround is to use "ipfs get" which works in under 7 seconds.

There maybe a way to fix "bacalhau get", but I was not able to get to the bottom of it.

**Comment by AquiGorka** [comment]
Wait, wait @arsen3d the end goal for this task is to find the ideal solution or if it cannot be done, document what is going on until us or the bacalhau team can provide the long term fix.
Reopening.

**Comment by Zorlin** [comment]
Re: this task:

I believe merging this "hack" (using IPFS get locally instead of bacalhau get) will be safe enough and reliable enough that we can rely on it during the next few weeks. We should also contact the Bacalhau team and open an issue that describes in detail the slowdown we're experiencing with `bacalhau get` and get a more permanent fix, as that should "always" be the faster option.

However, merging it as is seems prudent to me. It's a one line fix we can revert if it causes issues, will significantly improve the speed and the perception of the speed of Lilypad, and my concerns about propagation issues are irrelevant as we don't actually care if the IPFS CID is retrievable outside of the RP - the RP is literally going to send results to us over a websocket anyways, so firewall/NAT holepunching doesn't much matter.

**Comment by Zorlin** [comment]
> ![Image](https://private-user-images.githubusercontent.com/298235/330508172-37177007-8983-4e50-8571-043b140087c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4ODAxNTMsIm5iZiI6MTcxNTg3OTg1MywicGF0aCI6Ii8yOTgyMzUvMzMwNTA4MTcyLTM3MTc3MDA3LTg5ODMtNGU1MC04NTcxLTA0M2IxNDAwODdjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNzE3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzlhYTMyNDlmZjI3NjIyNDNkNWFiNjA4ZmIwNDcxYjM5ZTFhZWE1NDU3ZGQwY2E2ZmMwZDU0NDgyYTQzOGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3Sz1jVDbhmgOrej_NnYr1P1-IuPJQiv6vl5au-eVQ-8)
> 
> Yes. It's about the way "bacalhau get" attempts to get the file. Workaround is to use "ipfs get" which works in under 7 seconds.
> 
> There maybe a way to fix "bacalhau get", but I was not able to get to the bottom of it.

Can you please show me how to reproduce your testing here and how to get your UI work going so I may test this patch? I believe I can improve the speed further with IPFS peering/preload, at which point we should see < 2 second retrieval and can consider this solved until we get a more permanent fix from the Bacalhau team.

**Comment by walkah** [comment]
I think we're doing this now.
