### ISSUE TITLE
[core] Do we need any extra infra for prometheus/grafana?

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad#86]

**Comment by Zorlin** [comment]
longer term if we go to Prometheus, we'd simply use the Prometheus Helm charts and have k8s manage the Prometheus/Grafana infrastructure for us

short-to-medium term we'd like to use Grafana Cloud for this instead of managing our own infra - should literally work out cheaper than hosting it ourselves, once you account for infra/ops time

https://grafana.com/pricing/

Starts at "free", goes up once we start using it in anger, estimated cost is $50 to $100/month when we're fully spun up.

@DeveloperAlly Please give thoughts and approval for this spend - please reply with a good old "LGTM" and close if this is okay!

**Comment by DeveloperAlly** [comment]
Lgtm
